import Head from 'next/head'
import { NextPage, InferGetStaticPropsType } from 'next'
import { List, Title } from '@mantine/core'
import Link from 'next/link'

import { WPResponse } from '@/types'

type Props = InferGetStaticPropsType<typeof getStaticProps>

export const getStaticProps = async () => {
  const result = await fetch('https://muslim.or.id/wp-json/wp/v2/posts')
  const res = await result.json() as WPResponse[]

  return {
    props: {
      posts: res
    }
  }
}

const Home: NextPage<Props> = ({ posts }) => {
  return (
    <>
      <Head>
        <title>Artikel Islami</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Title order={1} mb={20}>Daftar posting</Title>
        { posts.length ? (
          <List>
            { posts.map(post => (
              <List.Item key={post.id}>
                <Link href={`/post/${post.id}`}>
                  {post.title.rendered}
                </Link>
              </List.Item>
            )) }
          </List>
        ) : <p>Tidak ada postingan</p>}
      </main>
    </>
  )
}

export default Home
