import Head from 'next/head'
import { NextPage, InferGetStaticPropsType } from 'next'
import { List, Title } from '@mantine/core'
import Link from 'next/link'

import { WPResponse } from '@/types'

type Props = InferGetStaticPropsType<typeof getStaticProps>

export const getStaticProps = async () => {
  const result = await fetch('http://localhost:8000/wp-json/wp/v2/news')
  const res = await result.json() as WPResponse[]

  return {
    props: {
      posts: res
    }
  }
}

const Home: NextPage<Props> = ({ posts }) => {
  return (
    <>
      <Head>
        <title>お知らせ一覧</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Title order={1} mb={20}>お知らせ一覧</Title>
        { posts.length ? (
          <List>
            { posts.map(post => (
              <List.Item key={post.id}>
                <Link href={`/news/${post.id}`}>
                  {post.title.rendered}
                </Link>
              </List.Item>
            )) }
          </List>
        ) : <p>投稿がありません</p>}
      </main>
    </>
  )
}

export default Home