import Head from 'next/head'
import { NextPage, InferGetStaticPropsType } from 'next'
import { Text, Title } from '@mantine/core'

import { WPResponse } from '@/types'

type Props = InferGetStaticPropsType<typeof getStaticProps>

export const getStaticProps = async () => {
  const result = await fetch('https://muslim.or.id/wp-json/wp/v2/pages/2')
  const res = await result.json() as WPResponse

  return {
    props: {
      post: res
    }
  }
}

const Home: NextPage<Props> = ({ post }) => {
  return (
    <>
      <Head>
        <title>{post.title.rendered}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Title order={1} mb={8}>{ post.title.rendered }</Title>
        <Text mb={20}><time>{post.modified}</time></Text>
        <div dangerouslySetInnerHTML={{ __html: post.content.rendered }} />
      </main>
    </>
  )
}

export default Home
